### ISSUE TITLE
An open question about the LICENSE

### ISSUE THREAD

**Issue by adulau** [0xThiebaut/Signatures#1]
Thanks for sharing the signature.

A small open question, can we consider the [license](https://github.com/0xThiebaut/Signatures/blob/main/LICENSE.md) open source? I suppose so but I'm wondering what the difference with this license and a BSD-2 clause license. Is there a specific goal compared to a BSD-2 clause license?

**Comment by 0xThiebaut** [comment]
Hi @adulau ,

The Detection Rule License (DRL) is indeed intended to be open source. As documented in the [SigmaHQ repository](https://github.com/SigmaHQ/Detection-Rule-License#detection-rule-license-drl) the main difference is that matches do require attribution as well whereas for BSD-2 the attribution is limited to source code and documentation. An example of valid DRL attribution is in VirusTotal.

![VirusTotal](https://user-images.githubusercontent.com/46688461/220951588-f4f0a882-fe7c-4953-9568-85074ba947a4.png)

Other repositories leveraging a similar license are [Neo23x0/signature-base](https://github.com/Neo23x0/signature-base/), [SigmaHQ/sigma](https://github.com/SigmaHQ/sigma#licenses) or [100DaysofYARA/2023](https://github.com/100DaysofYARA/2023). This repository is only a few minutes old so I haven't had time to set up the entire README's but will make sure to link to the [SigmaHQ/Detection-Rule-License](https://github.com/SigmaHQ/Detection-Rule-License#detection-rule-license-drl) repository.

Let me know if you have some concerns or additional questions!

**Comment by adulau** [comment]
Thanks a lot for the detailed explanation. I was just wondering about compatibility with other open source licenses with different rule-sets.
